FROM clojure:temurin-22-lein-jammy

WORKDIR /app

COPY project.clj /app/project.clj
COPY resources /app/resources
COPY src /app/src
COPY test /app/test
COPY scripts/entrypoint-supabase-provision.sh /usr/local/bin/entrypoint-supabase-provision.sh

RUN chmod +x /usr/local/bin/entrypoint-supabase-provision.sh && \
    lein deps

ENTRYPOINT ["/usr/local/bin/entrypoint-supabase-provision.sh"]
CMD ["schema"]
