"""Generate small application icon fonts, retaining full-font glyph fallbacks."""
import io
import json
import re
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.pens.recordingPen import DecomposingRecordingPen

ROOT = Path(__file__).resolve().parents[2]
PUBLIC = ROOT / "resources/public"


def unicode_ranges(points):
    ranges = []
    for point in sorted(points):
        if ranges and point == ranges[-1][1] + 1:
            ranges[-1][1] = point
        else:
            ranges.append([point, point])
    return ", ".join(f"U+{a:X}" if a == b else f"U+{a:X}-{b:X}" for a, b in ranges)


def face(family, weight, file, points, fallback=None):
    sources = f'url("/webfonts/{file}") format("woff2")'
    if fallback:
        sources += f', url("/webfonts/{fallback}") format("woff2")'
    return f'''@font-face {{
  font-family: "{family}";
  font-style: normal;
  font-weight: {weight};
  font-display: swap;
  src: {sources};
  unicode-range: {unicode_ranges(points)};
}}
'''


def main():
    catalog = json.loads((ROOT / "resources/icon-fonts.json").read_text())
    dynamic = catalog["dynamicIcons"]
    if not isinstance(dynamic, list) or not all(
        isinstance(name, str) and re.fullmatch(r"[a-z0-9-]+", name) for name in dynamic
    ):
        raise ValueError("dynamicIcons must contain icon names")
    css = (PUBLIC / "css/fontawesome.css").read_text()
    mapping = {name: int(code, 16) for name, code in re.findall(
        r'\.fa-([a-z0-9-]+):before\s*\{\s*content:\s*["\']\\([0-9a-f]+)', css
    )}
    missing = set(dynamic) - mapping.keys()
    if missing:
        raise ValueError(f"Dynamic icons absent from vendored CSS: {sorted(missing)}")
    names = set(dynamic)
    for source_root in [ROOT / "src/frontend", ROOT / "src/cljc", ROOT / "src/backend"]:
        for file in source_root.rglob("*.clj*"):
            names.update(re.findall(r"\bfa-([a-z0-9-]+)", file.read_text()))
    selected = {mapping[name] for name in names if name in mapping}
    outputs = {}
    styles = ["// Generated by bb fonts:icons; edit resources/icon-fonts.json instead.\n"
              "/*! Font Awesome Free: SIL OFL 1.1; https://fontawesome.com/license/free */\n"]
    for kind, weight, family in [("solid", 900, "Font Awesome 5 Free"),
                                 ("brands", 400, "Font Awesome 5 Brands")]:
        original = f"fa-{kind}-{weight}.woff2"
        target = f"fa-{kind}-{weight}-core.woff2"
        font = TTFont(PUBLIC / "webfonts" / original, recalcTimestamp=False, recalcBBoxes=False)
        cmap = dict(font.getBestCmap())
        core = selected & cmap.keys()
        if not core:
            raise ValueError(f"No {kind} icons selected")
        options = subset.Options()
        options.name_IDs = ["*"]
        options.glyph_names = True
        options.recalc_timestamp = False
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=core)
        subsetter.subset(font)
        # These are modified fonts; preserve copyright/license names and give
        # the derivative its own internal family/PostScript/unique identifiers.
        for record in font["name"].names:
            if record.nameID in {1, 3, 4, 6, 16}:
                value = f"tolgrAVen UI {kind.title()}"
                if record.nameID == 6:
                    value = value.replace(" ", "")
                record.string = value.encode(record.getEncoding())
        font.flavor = "woff2"
        data = io.BytesIO()
        font.save(data)
        data = data.getvalue()
        generated = TTFont(io.BytesIO(data))
        if set(generated.getBestCmap()) != core:
            raise ValueError(f"Unexpected glyph coverage in {target}")
        source = TTFont(PUBLIC / "webfonts" / original)
        before, after = source.getGlyphSet(), generated.getGlyphSet()
        for code, name in generated.getBestCmap().items():
            old_name = cmap[code]
            old_pen, new_pen = DecomposingRecordingPen(before), DecomposingRecordingPen(after)
            before[old_name].draw(old_pen)
            after[name].draw(new_pen)
            if (old_pen.value != new_pen.value
                    or source["hmtx"][old_name] != generated["hmtx"][name]):
                raise ValueError(f"Glyph geometry or metrics changed: {target}, U+{code:X}")
        outputs[PUBLIC / "webfonts" / target] = data
        styles += [face(family, weight, original, cmap.keys() - core),
                   face(family, weight, target, core, fallback=original)]
        print(f"{target}: {len(core)} glyphs, {len(data)} bytes")
    styles.append('''.fa, .fas { font-family: "Font Awesome 5 Free"; font-weight: 900; }
.fab { font-family: "Font Awesome 5 Brands"; font-weight: 400; }
''')
    outputs[ROOT / "resources/scss/generated/_icon-fonts.scss"] = "\n".join(styles).encode()
    # Finish generation/coverage checks before replacing any tracked output.
    for file, data in outputs.items():
        file.parent.mkdir(parents=True, exist_ok=True)
        temporary = file.with_suffix(file.suffix + ".tmp")
        temporary.write_bytes(data)
        temporary.replace(file)


if __name__ == "__main__":
    main()
