"""Export declared SVG icons and small fonts, retaining full-font fallbacks."""
import io
import json
import math
import re
import subprocess
from urllib.parse import quote
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.pens.recordingPen import DecomposingRecordingPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.transformPen import TransformPen

ROOT = Path(__file__).resolve().parents[2]
PUBLIC = ROOT / "resources/public"


def unicode_ranges(points):
    ranges = []
    for point in sorted(points):
        if ranges and point == ranges[-1][1] + 1:
            ranges[-1][1] = point
        else:
            ranges.append([point, point])
    return ", ".join(f"U+{a:X}" if a == b else f"U+{a:X}-{b:X}" for a, b in ranges)


def face(family, weight, file, points, fallback=None):
    sources = f'url("/webfonts/{file}") format("woff2")'
    if fallback:
        sources += f', url("/webfonts/{fallback}") format("woff2")'
    return f'''@font-face {{
  font-family: "{family}";
  font-style: normal;
  font-weight: {weight};
  font-display: swap;
  src: {sources};
  unicode-range: {unicode_ranges(points)};
}}
'''


def icon_definitions():
    # The same source reader supplies Shadow's CSS inventory; never evaluate
    # browser namespaces or keep a second list of component/module icons here.
    command = ["bb", "--classpath", "src/cljc", "-e",
               "(require '[tolgraven.build.modules :as modules] '[cheshire.core :as json]) "
               "(println (json/generate-string (modules/icon-definitions)))"]
    return json.loads(subprocess.check_output(command, cwd=ROOT, text=True))


def svg_icon(font, name):
    glyphs = font.getGlyphSet()
    width = glyphs[name].width
    ascent, descent = font["hhea"].ascent, font["hhea"].descent
    height = ascent - descent
    pen = SVGPathPen(glyphs, ntos=lambda number: f"{number:g}")
    glyphs[name].draw(TransformPen(pen, (1, 0, 0, -1, 0, ascent)))
    commands = pen.getCommands()
    if width <= 0 or height <= 0 or not commands:
        raise ValueError(f"Icon has no usable geometry: {name}")
    bounds = BoundsPen(glyphs)
    glyphs[name].draw(TransformPen(bounds, (1, 0, 0, -1, 0, ascent)))
    left, top, right, bottom = bounds.bounds
    # Round outward so serialized curve coordinates cannot overhang the viewport.
    left, top = min(0, math.floor(left)), min(0, math.floor(top))
    right, bottom = max(width, math.ceil(right)), max(height, math.ceil(bottom))
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" '
           f'viewBox="{left:g} {top:g} {right-left:g} {bottom-top:g}">'
           f'<path d="{commands}"/></svg>')
    # Expand the painted box, then restore the original advance/height with margins.
    # The empty inline block's baseline is its bottom margin edge, as before.
    layout = {"width": (right-left) / height,
              "height": (bottom-top) / height,
              "baseline": descent / height,
              "margins": (top / height, (width-right) / height,
                          (height-bottom) / height, left / height)}
    return svg, layout


def svg_outputs(mapping):
    outputs = {}
    fonts = {}
    for module, icons in icon_definitions().items():
        rules = ["// Generated by bb fonts:icons from module/component :icons.\n"
                 "/*! Font Awesome Free; https://fontawesome.com/license/free */\n"]
        for icon in icons:
            family, name = icon.split("/")
            weight = 400 if family == "brands" else 900
            if family not in fonts:
                fonts[family] = TTFont(PUBLIC / "webfonts" / f"fa-{family}-{weight}.woff2")
            font = fonts[family]
            cmap = font.getBestCmap()
            code = mapping.get(name)
            if code not in cmap:
                raise ValueError(f"Icon absent from its declared font family: {icon}")
            svg, layout = svg_icon(font, cmap[code])
            margins = " ".join(f"{value:g}em" for value in layout["margins"])
            outputs[PUBLIC / "img/icons/generated" / family / f"{name}.svg"] = (
                "<!-- Font Awesome Free; https://fontawesome.com/license/free -->\n" + svg + "\n"
            ).encode()
            selector = f".{'fab' if family == 'brands' else 'fas'}.fa-{name}"
            if family == "solid":
                selector += f", .fa.fa-{name}"
            # Inline the tiny SVG into its owner's CSS: no additional request,
            # font download, runtime conversion or swap for a declared icon.
            uri = "data:image/svg+xml," + quote(svg, safe="")
            before = ", ".join(part + "::before" for part in selector.split(", "))
            rules.append(f"{selector} {{ font-family: inherit; font-weight: inherit; }}\n"
                         f"{before} {{\n"
                         f"  content: \"\"; display: inline-block; width: {layout['width']:g}em; "
                         f"height: {layout['height']:g}em; margin: {margins};\n"
                         f"  vertical-align: {layout['baseline']:g}em; background-color: currentColor;\n"
                         f"  mask: url(\"{uri}\") center / 100% 100% no-repeat;\n"
                         f"}}\n")
        outputs[ROOT / "resources/scss/generated/icons" / f"_{module}.scss"] = "\n".join(rules).encode()
        if module != "main":
            outputs[ROOT / "resources/scss/modules" / f"icons-{module}.scss"] = (
                "// Generated by bb fonts:icons.\n" + f'@use "../generated/icons/{module}";\n'
            ).encode()
    # The common entry always exists, including sites declaring no common icons.
    outputs.setdefault(ROOT / "resources/scss/generated/icons/_main.scss",
                       b"// Generated by bb fonts:icons; no common icons declared.\n")
    return outputs


def main():
    catalog = json.loads((ROOT / "resources/icon-fonts.json").read_text())
    dynamic = catalog["dynamicIcons"]
    if not isinstance(dynamic, list) or not all(
        isinstance(name, str) and re.fullmatch(r"[a-z0-9-]+", name) for name in dynamic
    ):
        raise ValueError("dynamicIcons must contain icon names")
    css = (PUBLIC / "css/fontawesome.css").read_text()
    mapping = {name: int(code, 16) for name, code in re.findall(
        r'\.fa-([a-z0-9-]+):before\s*\{\s*content:\s*["\']\\([0-9a-f]+)', css
    )}
    missing = set(dynamic) - mapping.keys()
    if missing:
        raise ValueError(f"Dynamic icons absent from vendored CSS: {sorted(missing)}")
    names = set(dynamic)
    for source_root in [ROOT / "src/frontend", ROOT / "src/cljc", ROOT / "src/backend"]:
        for file in source_root.rglob("*.clj*"):
            names.update(re.findall(r"\bfa-([a-z0-9-]+)", file.read_text()))
    selected = {mapping[name] for name in names if name in mapping}
    outputs = svg_outputs(mapping)
    styles = ["// Generated by bb fonts:icons; edit resources/icon-fonts.json instead.\n"
              "/*! Font Awesome Free: SIL OFL 1.1; https://fontawesome.com/license/free */\n"]
    for kind, weight, family in [("solid", 900, "Font Awesome 5 Free"),
                                 ("brands", 400, "Font Awesome 5 Brands")]:
        original = f"fa-{kind}-{weight}.woff2"
        target = f"fa-{kind}-{weight}-core.woff2"
        font = TTFont(PUBLIC / "webfonts" / original, recalcTimestamp=False, recalcBBoxes=False)
        cmap = dict(font.getBestCmap())
        core = selected & cmap.keys()
        if not core:
            raise ValueError(f"No {kind} icons selected")
        options = subset.Options()
        options.name_IDs = ["*"]
        options.glyph_names = True
        options.recalc_timestamp = False
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=core)
        subsetter.subset(font)
        # These are modified fonts; preserve copyright/license names and give
        # the derivative its own internal family/PostScript/unique identifiers.
        for record in font["name"].names:
            if record.nameID in {1, 3, 4, 6, 16}:
                value = f"tolgrAVen UI {kind.title()}"
                if record.nameID == 6:
                    value = value.replace(" ", "")
                record.string = value.encode(record.getEncoding())
        font.flavor = "woff2"
        data = io.BytesIO()
        font.save(data)
        data = data.getvalue()
        generated = TTFont(io.BytesIO(data))
        if set(generated.getBestCmap()) != core:
            raise ValueError(f"Unexpected glyph coverage in {target}")
        source = TTFont(PUBLIC / "webfonts" / original)
        before, after = source.getGlyphSet(), generated.getGlyphSet()
        for code, name in generated.getBestCmap().items():
            old_name = cmap[code]
            old_pen, new_pen = DecomposingRecordingPen(before), DecomposingRecordingPen(after)
            before[old_name].draw(old_pen)
            after[name].draw(new_pen)
            if (old_pen.value != new_pen.value
                    or source["hmtx"][old_name] != generated["hmtx"][name]):
                raise ValueError(f"Glyph geometry or metrics changed: {target}, U+{code:X}")
        outputs[PUBLIC / "webfonts" / target] = data
        styles += [face(family, weight, original, cmap.keys() - core),
                   face(family, weight, target, core, fallback=original)]
        print(f"{target}: {len(core)} glyphs, {len(data)} bytes")
    styles.append('''.fa, .fas { font-family: "Font Awesome 5 Free"; font-weight: 900; }
.fab { font-family: "Font Awesome 5 Brands"; font-weight: 400; }
''')
    outputs[ROOT / "resources/scss/generated/_icon-fonts.scss"] = "\n".join(styles).encode()
    # Remove only outputs owned by this generator after all declarations validate.
    generated = [*(PUBLIC / "img/icons/generated").glob("*/*.svg"),
                 *(ROOT / "resources/scss/generated/icons").glob("_*.scss"),
                 *(ROOT / "resources/scss/modules").glob("icons-*.scss")]
    for file in generated:
        if (file not in outputs
                and (file.parent.name != "modules"
                     or file.read_text().startswith("// Generated by bb fonts:icons."))):
            file.unlink()
    # Finish generation/coverage checks before replacing any tracked output.
    for file, data in outputs.items():
        file.parent.mkdir(parents=True, exist_ok=True)
        temporary = file.with_suffix(file.suffix + ".tmp")
        temporary.write_bytes(data)
        temporary.replace(file)


if __name__ == "__main__":
    main()
